name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "0eb7580b-388b-48f5-8796-c6ccdeec754e"      # 替换为你创建的数据库 ID
